name: Latest blog post workflow
on:
  schedule:
    # Runs every Saturday at 7am
    - cron: '00 07 * * 6'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Added new blog post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@ronaldonyango"
          fail_on_error: false
