name: Update README

on:
  push:
    branches:
      - '*'  # Trigger on all branches
  workflow_dispatch: # Enable manual triggering

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read metadata
        id: read_metadata
        run: |
          totalViews=$(jq -r '.totalViews' ronaldonyango/global-suicide-rates-1990-to-2022.json)
          totalDownloads=$(jq -r '.totalDownloads' ronaldonyango/global-suicide-rates-1990-to-2022.json)
          echo "Total Views: $totalViews"
          echo "Total Downloads: $totalDownloads"
          echo "::set-output name=totalViews::$totalViews"
          echo "::set-output name=totalDownloads::$totalDownloads"

      - name: Update README
        run: |
          sed -i "s|\[!\[Total Views\](.*)\]|![Total Views](http://img.shields.io/badge/Total%20Views-${{ steps.read_metadata.outputs.totalViews }}-blue)|" README.md
          sed -i "s|\[!\[Total Downloads\](.*)\]|![Total Downloads](http://img.shields.io/badge/Total%20Downloads-${{ steps.read_metadata.outputs.totalDownloads }}-brightgreen)|" README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README with latest dataset stats
