name: Update README

on:
  push:
    branches:
      - master
  workflow_dispatch: # Enable manual triggering

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read metadata
        id: read_metadata
        run: |
          metadata=$(< ronaldonyango/global-suicide-rates-1990-to-2022.json)
          totalViews=$(echo "$metadata" | jq -r '.totalViews')
          totalDownloads=$(echo "$metadata" | jq -r '.totalDownloads')
          echo "Total Views: $totalViews"
          echo "Total Downloads: $totalDownloads"
          echo "::set-output name=totalViews::$totalViews"
          echo "::set-output name=totalDownloads::$totalDownloads"

      - name: Generate badges
        id: generate_badges
        run: |
          totalViewsBadge="[![Total Views](http://img.shields.io/badge/Total%20Views-$((totalViews))-blue)]"
          totalDownloadsBadge="[![Total Downloads](http://img.shields.io/badge/Total%20Downloads-$((totalDownloads))-brightgreen)]"
          echo "::set-output name=totalViewsBadge::$totalViewsBadge"
          echo "::set-output name=totalDownloadsBadge::$totalDownloadsBadge"

      - name: Update README
        run: |
          sed -i "s|\[!\[Total Views\]\(.*\)\]|${{ steps.generate_badges.outputs.totalViewsBadge }}|" README.md
          sed -i "s|\[!\[Total Downloads\]\(.*\)\]|${{ steps.generate_badges.outputs.totalDownloadsBadge }}|" README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README with latest dataset stats
